//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recursos {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_CSS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_CSS() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Recursos.Resource_CSS", typeof(Resource_CSS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /* Page */
        ///body,html,div,blockquote,img,label,p,h1,h2,h3,h4,h5,h6,pre,ul,ol,li,dl,dt,dd,form,a,fieldset,input,th,td{border:0;outline:none;margin:0;padding:0;}
        ///ul, ul li{list-style: none;}
        ///ul.text {margin-bottom: 1em; line-height: 1.5em;}
        ///.text-center {text-align: center;}
        ///body {font: normal 13px Arial, sans-serif;}
        ///h2 {font: normal 26px Arial, sans-serif; padding: 20px 0; margin: 0 0 30px 0;}
        ///.wrap {width: 960px; margin: 0 auto;}
        ///.demo-container {padding: 0px; float: left; width: 260px;}
        ///.demo-cont [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string dcaccordion_css {
            get {
                return ResourceManager.GetString("dcaccordion_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /* Text Styles */
        ///hr { color: #000000}
        ///body, table /* Normal */
        ///{
        /// font-size: 10pt;
        /// font-family: &apos;Tahoma&apos;;
        /// font-style: normal;
        /// font-weight: normal;
        /// color: #000000;
        /// text-decoration: none;
        ///}
        ///span.f_CodeExample /* Code Example */
        ///{
        /// font-size: 8pt;
        /// font-family: &apos;Verdana&apos;;
        /// color: #4b4e79;
        /// vertical-align: sub;
        ///}
        ///span.f_Comment /* Comment */
        ///{
        ///}
        ///span.f_Conttopicos /* Cont topicos */
        ///{
        /// font-size: 8pt;
        /// font-family: &apos;Verdana&apos;;
        /// color: #515151;
        ///}
        ///span.f_Conttópicos /* Cont tópicos [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string default_css {
            get {
                return ResourceManager.GetString("default_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .grey .accordion{font: bold 12px Arial, sans-serif; border-top: 1px solid #33ccff; border-right: 1px solid #33ccff; border-left: 1px solid #33ccff;}
        ///.grey .accordion, .grey .accordion li {margin: 0; padding: 0; border: none;}
        ///.grey .accordion a {padding: 10px 10px 10px 50px; background: #00a3e7; text-decoration:none; display: block; color: #ffffcc; border-bottom: 1px solid #33ccff; border-top: 1px solid #fff; position: relative;}
        ///.grey .accordion a.dcjq-parent, .grey .accordion a.dcjq-parent:hover {backg [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string grey_css {
            get {
                return ResourceManager.GetString("grey_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a body {
        ///       background: #FFFFFF;
        ///    }
        ///
        ///html, body {  
        ///             min-height: 100%; /*Sets the min height to the   height of the viewport.*/  
        ///             width: 100%;  height: 100%; /*Effectively, this is min height   
        ///                                                  for IE5+/Win, since IE wrongly expands   
        ///                                                  an element to enclose its content.   
        ///                                                  This mis-behavior screws up modern    
        ///         [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string PortalCFG_css {
            get {
                return ResourceManager.GetString("PortalCFG_css", resourceCulture);
            }
        }
    }
}
