//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recursos {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_JS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_JS() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Recursos.Resource_JS", typeof(Resource_JS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /*!
        /// * jQuery Cookie Plugin v1.4.1
        /// * https://github.com/carhartl/jquery-cookie
        /// *
        /// * Copyright 2006, 2014 Klaus Hartl
        /// * Released under the MIT license
        /// */
        ///(function (factory) {
        ///	if (typeof define === &apos;function&apos; &amp;&amp; define.amd) {
        ///		// AMD (Register as an anonymous module)
        ///		define([&apos;jquery&apos;], factory);
        ///	} else if (typeof exports === &apos;object&apos;) {
        ///		// Node/CommonJS
        ///		module.exports = factory(require(&apos;jquery&apos;));
        ///	} else {
        ///		// Browser globals
        ///		factory(jQuery);
        ///	}
        ///}(function ($) {
        ///
        ///	var plu [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string jquery_cookie_js {
            get {
                return ResourceManager.GetString("jquery_cookie_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /*
        /// * DC jQuery Vertical Accordion Menu - jQuery vertical accordion menu plugin
        /// * Copyright (c) 2011 Design Chemical
        /// *
        /// * Dual licensed under the MIT and GPL licenses:
        /// * 	http://www.opensource.org/licenses/mit-license.php
        /// * 	http://www.gnu.org/licenses/gpl.html
        /// *
        /// */
        ///
        ///(function($){
        ///
        ///	$.fn.dcAccordion = function(options) {
        ///
        ///		//set default options 
        ///		var defaults = {
        ///			classParent	 : &apos;dcjq-parent&apos;,
        ///			classActive	 : &apos;active&apos;,
        ///			classArrow	 : &apos;dcjq-icon&apos;,
        ///			classCount	 : &apos;dcjq-count [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string jquery_dcjqaccordion_2_7_min_js {
            get {
                return ResourceManager.GetString("jquery_dcjqaccordion_2_7_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /**
        ///* hoverIntent r6 // 2011.02.26 // jQuery 1.5.1+
        ///* &lt;http://cherne.net/brian/resources/jquery.hoverIntent.html&gt;
        ///* 
        ///* @param  f  onMouseOver function || An object with configuration options
        ///* @param  g  onMouseOut function  || Nothing (use configuration options object)
        ///* @author    Brian Cherne brian(at)cherne(dot)net
        ///*/
        ///(function($){$.fn.hoverIntent=function(f,g){var cfg={sensitivity:7,interval:100,timeout:0};cfg=$.extend(cfg,g?{over:f,out:g}:f);var cX,cY,pX,pY;var track=function(ev){cX=ev.pageX;cY=ev.pag [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string jquery_hoverIntent_minified_js {
            get {
                return ResourceManager.GetString("jquery_hoverIntent_minified_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /*! jQuery v1.7.1 jquery.com | jquery.org/license */
        ///(function(a,b){function cy(a){return f.isWindow(a)?a:a.nodeType===9?a.defaultView||a.parentWindow:!1}function cv(a){if(!ck[a]){var b=c.body,d=f(&quot;&lt;&quot;+a+&quot;&gt;&quot;).appendTo(b),e=d.css(&quot;display&quot;);d.remove();if(e===&quot;none&quot;||e===&quot;&quot;){cl||(cl=c.createElement(&quot;iframe&quot;),cl.frameBorder=cl.width=cl.height=0),b.appendChild(cl);if(!cm||!cl.createElement)cm=(cl.contentWindow||cl.contentDocument).document,cm.write((c.compatMode===&quot;CSS1Compat&quot;?&quot;&lt;!doctype html&gt;&quot;:&quot;&quot;)+&quot;&lt;html&gt;&lt;body&gt; [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string jquery_min_js {
            get {
                return ResourceManager.GetString("jquery_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /*! jQuery UI - v1.12.0 - 2016-07-08
        ///* http://jqueryui.com
        ///* Includes: widget.js, position.js, data.js, disable-selection.js, effect.js, effects/effect-blind.js, effects/effect-bounce.js, effects/effect-clip.js, effects/effect-drop.js, effects/effect-explode.js, effects/effect-fade.js, effects/effect-fold.js, effects/effect-highlight.js, effects/effect-puff.js, effects/effect-pulsate.js, effects/effect-scale.js, effects/effect-shake.js, effects/effect-size.js, effects/effect-slide.js, effects/effect-transfe [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string jquery_ui_js {
            get {
                return ResourceManager.GetString("jquery_ui_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /*
        ///    http://www.JSON.org/json2.js
        ///    2011-02-23
        ///
        ///    Public Domain.
        ///
        ///    NO WARRANTY EXPRESSED OR IMPLIED. USE AT YOUR OWN RISK.
        ///
        ///    See http://www.JSON.org/js.html
        ///
        ///
        ///    This code should be minified before deployment.
        ///    See http://javascript.crockford.com/jsmin.html
        ///
        ///    USE YOUR OWN COPY. IT IS EXTREMELY UNWISE TO LOAD CODE FROM SERVERS YOU DO
        ///    NOT CONTROL.
        ///
        ///
        ///    This file creates a global JSON object containing two methods: stringify
        ///    and parse.
        ///
        ///        JSON.stringify(value, replacer, space) [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string json2_js {
            get {
                return ResourceManager.GetString("json2_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /*!
        /// * Knockout JavaScript library v3.4.0
        /// * (c) Steven Sanderson - http://knockoutjs.com/
        /// * License: MIT (http://www.opensource.org/licenses/mit-license.php)
        /// */
        ///
        ///(function() {(function(n){var x=this||(0,eval)(&quot;this&quot;),u=x.document,M=x.navigator,v=x.jQuery,F=x.JSON;(function(n){&quot;function&quot;===typeof define&amp;&amp;define.amd?define([&quot;exports&quot;,&quot;require&quot;],n):&quot;object&quot;===typeof exports&amp;&amp;&quot;object&quot;===typeof module?n(module.exports||exports):n(x.ko={})})(function(N,O){function J(a,c){return null===a||typeof a in T?a===c:!1 [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string knockout_js {
            get {
                return ResourceManager.GetString("knockout_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /// Knockout Mapping plugin v2.4.1
        ////// (c) 2013 Steven Sanderson, Roy Jacobs - http://knockoutjs.com/
        ////// License: MIT (http://www.opensource.org/licenses/mit-license.php)
        ///(function (factory) {
        ///	// Module systems magic dance.
        ///
        ///	if (typeof require === &quot;function&quot; &amp;&amp; typeof exports === &quot;object&quot; &amp;&amp; typeof module === &quot;object&quot;) {
        ///		// CommonJS or Node: hard-coded dependency on &quot;knockout&quot;
        ///		factory(require(&quot;knockout&quot;), exports);
        ///	} else if (typeof define === &quot;function&quot; &amp;&amp; define[&quot;amd&quot;]) {
        ///		// AMD anonymous [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string knockout_mapping_latest_debug_js {
            get {
                return ResourceManager.GetString("knockout_mapping_latest_debug_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /// Knockout Mapping plugin v2.4.1
        ////// (c) 2013 Steven Sanderson, Roy Jacobs - http://knockoutjs.com/
        ////// License: MIT (http://www.opensource.org/licenses/mit-license.php)
        ///(function(e){&quot;function&quot;===typeof require&amp;&amp;&quot;object&quot;===typeof exports&amp;&amp;&quot;object&quot;===typeof module?e(require(&quot;knockout&quot;),exports):&quot;function&quot;===typeof define&amp;&amp;define.amd?define([&quot;knockout&quot;,&quot;exports&quot;],e):e(ko,ko.mapping={})})(function(e,f){function y(b,c){var a,d;for(d in c)if(c.hasOwnProperty(d)&amp;&amp;c[d])if(a=f.getType(b[d]),d&amp;&amp;b[d]&amp;&amp;&quot;array&quot;!==a&amp;&amp; [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string knockout_mapping_latest_js {
            get {
                return ResourceManager.GetString("knockout_mapping_latest_js", resourceCulture);
            }
        }
    }
}
