//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recursos {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Recursos.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_grey_down_png {
            get {
                object obj = ResourceManager.GetObject("arrow_grey_down_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_grey_right_png {
            get {
                object obj = ResourceManager.GetObject("arrow_grey_right_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///   &lt;title&gt;Menu Principal&lt;/title&gt;
        ///   &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=iso-8859-1&quot; /&gt;
        /// 
        ///   &lt;meta http-equiv=&quot;Content-Style-Type&quot; content=&quot;text/css&quot; /&gt;
        ///
        ///&lt;body&gt;
        ///&lt;script type=&quot;text/javascript&quot;&gt;
        ///            top.window.location=&apos;menutree_principal?{&quot;login&quot;:&quot;!XLOGIN!&quot;,&quot;sessao&quot;:&quot;!XSESSAO!&quot;}&apos;;
        ///&lt;/script&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string autentica_login {
            get {
                return ResourceManager.GetString("autentica_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg_grey_png {
            get {
                object obj = ResourceManager.GetObject("bg_grey_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;PortalCFG&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;script type=&quot;text/javascript&quot; src=&quot;jquery.min.js&quot;&gt;&lt;/script&gt;
        ///    &lt;script type=&apos;text/javascript&apos; src=&apos;knockout.js&apos;&gt;&lt;/script&gt;
        ///    &lt;script type=&quot;text/javascript&quot; src=&quot;json2.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;style&gt;
        ///
        ///    .posicionar {
        ///        position: absolute;
        ///        margin: auto;
        ///    }
        ///&lt;/style&gt;
        ///
        ///&lt;body&gt;
        ///
        ///    &lt;table widt [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Cabe&amp;ccedilalho do Menu&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=ISO-8859-1&quot;&gt;
        ///    &lt;script type=&quot;text/javascript&quot; src=&quot;jquery.min.js&quot;&gt;&lt;/script&gt;
        ///
        ///&lt;script type=&quot;text/javascript&quot;&gt;
        ///
        ///function fMeudiv(cTrace, cValor) {
        ///       if  (cTrace == &apos;&apos;) {
        ///           document.form1.cTrace.value =  cValor;
        ///       } else {
        ///           document.form1.cTrace.value =  cTrace+cValor;
        ///      }
        ///
        ///     [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string menutree_cabecalho {
            get {
                return ResourceManager.GetString("menutree_cabecalho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///&lt;meta name=&quot;robots&quot; content=&quot;all&quot; /&gt;
        ///&lt;meta charset=&apos;UTF-8&apos;&gt;
        ///&lt;title&gt;PortalCFG&lt;/title&gt;
        ///&lt;link href=&quot;/css/dcaccordion.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; /&gt;
        ///&lt;script type=&quot;text/javascript&quot; src=&quot;jquery.min.js&quot;&gt;&lt;/script&gt;
        ///&lt;script type=&apos;text/javascript&apos; src=&apos;jquery.cookie.js&apos;&gt;&lt;/script&gt;
        ///&lt;script type=&apos;text/javascript&apos; src=&apos;jquery.hoverIntent.minifie [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string menutree_esquerdo {
            get {
                return ResourceManager.GetString("menutree_esquerdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional-dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;title&gt;Tela Explicativa&lt;/title&gt;
        ///
        ///   &lt;meta content=&quot;text/html;charset=ISO-8859-1&quot; http-equiv=&quot;Content-Type&quot;&gt;
        ///
        ///   &lt;link type=&quot;text/css&quot; href=&quot;default.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;margin:0px 0px 0px 0px; background-color:#FFFFFF;&quot; &gt;
        ///&lt;div id=&quot;hmpopupDiv&quot; style=&quot;visibility:hidden; position:absolute; z-index:10 [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string menutree_explicativo {
            get {
                return ResourceManager.GetString("menutree_explicativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;meta content=&quot;text/html;charset=ISO-8859-1&quot; http-equiv=&quot;Content-Type&quot;&gt;
        ///&lt;META HTTP-EQUIV=&quot;PRAGMA&quot; CONTENT=&quot;NO-CACHE&quot;&gt;
        ///
        ///&lt;script type=&quot;text/javascript&quot;&gt;
        ///
        ///function Contrair(dimensao){
        ///    if( Frame2.cols==dimensao ) {
        ///        Frame2.cols=&quot;200,6,*&quot;;
        ///    } else {
        ///        Frame2.cols=dimensao;
        ///        hmnavigation.scrolling=&quot;no&quot;;
        ///    }
        ///}
        ///
        ///&lt;/script&gt;
        ///
        ///&lt;/head&gt;
        ///
        ///  &lt;frameset id=&quot;Frame1&quot; name=&quot;Frame1&quot; rows=&quot;90,*&quot; frameborder=&quot;0&quot; framespacing=&quot;1&quot;&gt;
        ///  &lt;frame id=&quot;hmheader&quot; name=&quot;hmheader&quot; [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string menutree_principal {
            get {
                return ResourceManager.GetString("menutree_principal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///    
        ///    &lt;meta name=&quot;generator&quot; content=&quot;PORTALCFG&quot;&gt;
        ///    &lt;meta name=&quot;created&quot; content=&quot;sex, 17 jun 2011 13:05:43 GMT&quot;&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///    &lt;meta name=&quot;keywords&quot; content=&quot;&quot;&gt;
        ///    &lt;meta charset=&apos;UTF-8&apos;&gt;
        ///    &lt;title&gt;PortalCFG&lt;/title&gt;
        ///    &lt;script type=&quot;text/javascript&quot; src=&quot;json2.js&quot;&gt;&lt;/script&gt;
        ///    &lt;script type=&quot;text/javascript&quot; src=&quot;jquery.min.js&quot;&gt;&lt;/script&gt;
        ///    &lt;script type=&apos;text/javascript&apos; src=&apos;knockout.js&apos;&gt;&lt;/script&gt;
        ///    &lt;script type=&quot;text/ja [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string pagina_browser {
            get {
                return ResourceManager.GetString("pagina_browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap portal_edit_gif {
            get {
                object obj = ResourceManager.GetObject("portal_edit_gif", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap portal_mais_gif {
            get {
                object obj = ResourceManager.GetObject("portal_mais_gif", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap portal_visualizar_gif {
            get {
                object obj = ResourceManager.GetObject("portal_visualizar_gif", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;PortalCFG&lt;/title&gt;
        ///    &lt;meta charset=&apos;UTF-8&apos;&gt;
        /// 
        ///	&lt;link href=&quot;PortalCFG.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; /&gt;    
        ///
        ///	&lt;script type=&quot;text/javascript&quot;&gt;
        ///
        ///		function toJSONString( form ) {
        ///			var obj = {};
        ///			var elements = form.querySelectorAll( &quot;input, select, textarea&quot; );
        ///			for( var i = 0; i &lt; elements.length; ++i ) {
        ///				var element = elements[i];
        ///				var name = element.id;  //Obtem pelo id, retirar a pro [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string tabelas_filtro {
            get {
                return ResourceManager.GetString("tabelas_filtro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap topo_fundo_png {
            get {
                object obj = ResourceManager.GetObject("topo_fundo_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap topo_logo_png {
            get {
                object obj = ResourceManager.GetObject("topo_logo_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap topo1_fundo_gif {
            get {
                object obj = ResourceManager.GetObject("topo1_fundo_gif", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui_bg_highlight_soft_75_azul_1x100_png {
            get {
                object obj = ResourceManager.GetObject("ui_bg_highlight_soft_75_azul_1x100_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
